### ISSUE TITLE
Not working for me

### ISSUE THREAD

**Issue by Animizio** [im85288/service.nextup.notification#56] opened 2018-05-29 11:13 UTC
Cant get it to work..
Next Episode wont Start and Also no messages or pictures.
I m using Streams, which are ported into the library. I need some more addons installed? Or settings? I m using the aura skin, but the developer said for him its working with this skin.
I hope you can help me to fix and use this. 
Thank you

The log:

18:36:49.468 T:138841887824  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got active player {"id":1,"jsonrpc":"2.0","result":[{"playerid":1,"type":"video"}]}
18:36:49.470 T:138841887824  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Getting details of now  playing media
18:36:49.515 T:138841887824  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Got details of now playing media{"id":1,"jsonrpc":"2.0","result":{"item":{"episode":1,"genre":[],"label":"Bube, Dame, König, Shawn und Burtons Feuerkelch","playcount":0,"season":8,"showtitle":"","tvshowid":-1,"type":"unknown"}}}
18:36:49.774 T:138841887824  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Fetched missing tvshowid -1
18:36:49.776 T:138841887824  NOTICE: NEXTUP SERVICE NOTIFICATION Player -> logMsg : Error: cannot determine if episode
18:36:49.777 T:138841887824  NOTICE: NEXTUP SERVICE NOTIFICATION Service -> logMsg : Netflix style autoplay succeeded

**Comment by Animizio** [comment] 2018-05-31 17:58
Found this thread:
https://github.com/im85288/service.nextup.notification/issues/30#issuecomment-393596595

Looks like Streams are supported? But well, its not working right now for me with Streams.. Maybe It needs a fix?

**Comment by hawkeyexp** [comment] 2018-06-05 21:44
Problem is caused by source addon which does not declare if content is episode etc. -> 'type unknown'
Fix must be done in this addon. Nothing related to skin.

**Comment by Animizio** [comment] 2018-06-09 09:30
Okay I tested a lot now.
I dont think its the addon, because its sometimes working with it and sometimes dont.
For example its working on the kodi18 millhouse build, but Not for official kodi 17 oder kodi18 alpha.
So, its not skin fault, Not addons fault. But I think something is missing, which is added in the millhouse build.

**Comment by Animizio** [comment] 2018-06-10 20:05
Okay I tested some more. 
Seems like its working with every Addon I tested on kodi18 builds.
But Its not working for kodi17.
Any ideas?

**Comment by im85288** [comment] 2018-12-18 18:06
Closed as this addon is no longer supported

**Closed as completed by im85288** 2018-12-18 18:06 UTC
